### ISSUE TITLE
Latest build not available anymore

### ISSUE THREAD

**Issue by GigaDroid** [velopack/velopack.fusion#8]
Hey, the build artifacts appear to have expired. I'm trying to build an integration just using the Fusion CLI so would be great to have access to the latest build without having to build it myself. Would probably be best to have the latest build as a Github Release.

**Comment by caesay** [comment]
Heya, you can download the latest build by running `npm pack velopack` in your terminal, and then extracting the binaries from the `velopack-{version}.tgz` file that will be created. What language are you integrating Velopack with?

**Comment by GigaDroid** [comment]
Okay thanks, didn't know that! I'm planning to integrate it into Flutter

**Comment by caesay** [comment]
If you have any questions, please feel free to join our Discord. I'd love to eventually have official support for Flutter/Dart but don't know much about it myself.
